-- 腾讯云直播配置字段
-- 为 sys_company_conf 表添加腾讯云直播相关配置字段

USE `skyserver`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 检查并添加字段
ALTER TABLE `sys_company_conf`
ADD COLUMN IF NOT EXISTS `TENCENT_CLOUD_SECRET_ID` varchar(255) DEFAULT NULL COMMENT '腾讯云SecretID',
ADD COLUMN IF NOT EXISTS `TENCENT_CLOUD_SECRET_KEY` varchar(255) DEFAULT NULL COMMENT '腾讯云SecretKey',
ADD COLUMN IF NOT EXISTS `TENCENT_CLOUD_REGION` varchar(255) DEFAULT NULL COMMENT '腾讯云区域',
ADD COLUMN IF NOT EXISTS `TENCENT_CLOUD_CALLBACK_KEY` varchar(255) DEFAULT NULL COMMENT '腾讯云回调密钥';

SET FOREIGN_KEY_CHECKS = 1;
