-- 创建直播间表
CREATE TABLE IF NOT EXISTS `live_room` (
  `ID` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `SYS_COMPANY_ID` bigint unsigned NOT NULL COMMENT '公司ID',
  `ROOM_NAME` varchar(255) NOT NULL COMMENT '直播间名称',
  `ROOM_TYPE` varchar(50) NOT NULL COMMENT '直播间类型：video(视频直播), image(图片直播), vr(VR直播), audio(语音直播), graphic(图文直播)',
  `BROADCAST_FORMAT` varchar(50) NOT NULL COMMENT '播出形式：live(直播), vod(点播/录播), pseudo(伪直播)',
  `ROOM_STAGE` varchar(50) NOT NULL COMMENT '直播间阶段：formal(正式直播), test(测试直播)',
  `DISPLAY_MODE` varchar(50) DEFAULT NULL COMMENT '显示方式：landscape(横屏), portrait(竖屏), three_screen(三分屏)',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `COVER_IMAGE` varchar(500) DEFAULT NULL COMMENT '直播间封面',
  `VIEWING_METHOD` varchar(50) NOT NULL DEFAULT 'public' COMMENT '观看方式：public(公开), encrypted(加密), paid(付费), ticket(购票进入), enterprise(企业成员观看), custom(自建成员观看)',
  `VIEWING_PASSWORD` varchar(255) DEFAULT NULL COMMENT '观看密码（加密观看时使用）',
  `VIEWING_PRICE` decimal(10,2) DEFAULT NULL COMMENT '观看价格（付费观看时使用）',
  `PLAYBACK_METHOD` varchar(50) NOT NULL DEFAULT 'post_end' COMMENT '回放方式：post_end(结束后回放), real_time(实时回放), no_playback(结束后不回放)',
  `PLAYBACK_VALIDITY` varchar(50) DEFAULT 'unlimited' COMMENT '回放有效期：unlimited(无限制), all_day(全天), partial(部分时段)',
  `PLAYBACK_START_TIME` time DEFAULT NULL COMMENT '回放开始时间（部分时段时使用）',
  `PLAYBACK_END_TIME` time DEFAULT NULL COMMENT '回放结束时间（部分时段时使用）',
  `STREAM_NAME` varchar(255) DEFAULT NULL COMMENT '流名称',
  `PUSH_URL` varchar(500) DEFAULT NULL COMMENT '推流地址',
  `PLAY_URL` varchar(500) DEFAULT NULL COMMENT '播放地址',
  `STATUS` varchar(50) NOT NULL DEFAULT 'draft' COMMENT '状态：draft(草稿), scheduled(已排期), live(直播中), ended(已结束), archived(已归档)',
  `VIEWER_COUNT` int NOT NULL DEFAULT '0' COMMENT '观看人数',
  `PEAK_VIEWER_COUNT` int NOT NULL DEFAULT '0' COMMENT '峰值观看人数',
  `DURATION` int NOT NULL DEFAULT '0' COMMENT '直播时长（秒）',
  `DESCRIPTION` text COMMENT '直播间描述',
  `PROPS` text COMMENT '扩展属性（JSON）',
  `CREATE_BY` varchar(80) DEFAULT NULL COMMENT '创建人',
  `CREATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_BY` varchar(80) DEFAULT NULL COMMENT '更新人',
  `UPDATE_TIME` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `IS_ACTIVE` char(1) NOT NULL DEFAULT 'Y' COMMENT '是否有效：Y(有效), N(无效)',
  PRIMARY KEY (`ID`),
  KEY `idx_sys_company_id` (`SYS_COMPANY_ID`),
  KEY `idx_room_type` (`ROOM_TYPE`),
  KEY `idx_stream_name` (`STREAM_NAME`),
  KEY `idx_status` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='直播间表';
